### ISSUE TITLE
package.json should not be in src but at the root of the project

### ISSUE THREAD

**Issue by locness3** [padscape/api#6]
@BonfireScratch

**Comment by BonfireScratch** [comment]
@locness3 what about `package-lock.json`?

**Comment by locness3** [comment]
same

**Comment by locness3** [comment]
because your package is your source _and_ your assets etc.

**Comment by BonfireScratch** [comment]
@locness3 OK

**Comment by BonfireScratch** [comment]
How do I run `npm init` from an unrelated directory? I can't get it working.

**Comment by BonfireScratch** [comment]
@locness3 https://github.com/padscape/api/commit/8d2a333243e8664afc825395fd7e77b60b11c37f
